apiVersion: v1alpha1
kind: Role
metadata:
  name: bark-role-manage-bark
  labels:
    abaaba.cloud/role-template: "true"
  annotations:
    rbac.authorization.abaaba.cloud/module: "Bark Management"
    rbac.authorization.abaaba.cloud/display-name: "Manage Bark"
    rbac.authorization.abaaba.cloud/ui-permissions: |
      ["plugin:bark:bark:manage"]
rules:
  - apiGroups: ["console.api.bark.abaaba.cloud"]
    resources: ["bark/test"]
    verbs: ["create"]